title: Brasil em Números
description: Uma plataforma dedicada a fornecer dados e informações sobre o Brasil.
tagline: "Dados e informações sobre o Brasil em um só lugar"
baseurl: "/"
url: "https://www.brasilemnumeros.ong.br"
github_username: brasilemnumeros

plugins:
  - jekyll-analytics
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - CNAME
  - package.json
  - package-lock.json

google_analytics: G-N4CFQ7CL1S
