title: Brasil em Números
description: Uma plataforma dedicada a fornecer dados e informações sobre o Brasil.
tagline: "Dados e informações sobre o Brasil em um só lugar"
baseurl: "/"
url: "https://www.brasilemnumeros.ong.br"
github_username: brasilemnumeros

# Blog Categories
blog_categories:
  analises:
    name: "Análises"
    description: "Análises aprofundadas dos indicadores econômicos brasileiros"
    icon: "📊"
    color: "blue"
  indicadores:
    name: "Indicadores"
    description: "Novidades sobre indicadores econômicos disponíveis no site"
    icon: "📈"
    color: "green"
  noticias:
    name: "Notícias"
    description: "Novidades e atualizações do projeto Brasil em Números"
    icon: "📢"
    color: "purple"

plugins:
  - jekyll-analytics
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - CNAME
  - package.json
  - package-lock.json

google_analytics: G-N4CFQ7CL1S
